### ISSUE TITLE
avoidOverlaps + alignment constraint produces graph displacement on start()

### ISSUE THREAD

**Issue by doublemarked** [tgdwyer/WebCola#215]
I've been chasing down a problem with our graph in which on update everything displaces slightly. After some debugging I've narrowed it down to the following conditions,

- avoidOverlaps(true)
- handleDisconnected(false)
- An axis alignment constraint

Under these conditions, repeated calls to start() will cause all nodes in the graph to skip their way across the canvas. An easiest way to reproduce is as follows,

  1. Open http://marvl.infotech.monash.edu/webcola/examples/alignment.html
  2. In the dev console: `d3cola.handleDisconnected(false)`
  3. In the dev console: `d3cola.start()`
  4. Repeat step 3 enough times to watch the graph limp off screen

Note: handleDisconnected has to be disabled because when enabled it centers the graph w/ each call to start(), which obscures the problem.

Any thoughts? We're trying to reduce disturbances to the graph as we interact with it (which includes adding/removing nodes and other things that are requiring a later call to start()). We're disabling handleDisconnected because of this centering it does (which disturbs a translated graph).

**Comment by tgdwyer** [comment]
Thanks for the simple repro.  Please test the fix I just pushed on your own graph and let me know how it goes.

**Comment by doublemarked** [comment]
Hey @tgdwyer - thanks for such a fast reply! As it turns out this patch does not fix the problem in our own project. In our project the effect is much less pronounced than what I showed you in the alignment example. 

In our project the nodes all nudge to the right by a single pixel. I've spent some time today debugging it further and believe I better understand the conditions. In addition to those listed above, the constraints applied in our simulation produce links that are under tension. I believe this link tension causes two nodes to press against one another, causing the simulation to displace when avoidOverlaps is calculated. Under these circumstances, calling start() causes the entire graph to offset by 1 pixel along one or two axis. 

I've created a small example to demonstrate the situation,

   http://embed.plnkr.co/qc98e1/

Here's how you should use it,

1. The initial linkDistance is 120. Click the Start button to call the start() function 100 times and confirm that no graph displacement takes place under these conditions.
2. Click the "linkDistance(30)" button to reduce the link distance to 30.
3. Press the Start button again. You should now observe the graph shift to the right. 

I tried a number of tweaks to this test but was not able to simplify it further. I believe the displacement is occurring because the green and yellow nodes are being pressed against one another. If I add an additional constraint to keep a gap between these nodes the problem goes away. You'll find that constraint commented out in the code.

Ok, so all this said - actually I consider it a bug in our code that our graph was under such tension. It was caused by our node sizes in the simulation being larger than the DOM element we were rendering, which made it not immediately noticeable.

**Comment by tgdwyer** [comment]
so that one pixel that you saw it crawling by was precisely the 1 pixel of padding I was putting in in my brain-dead constraint feasibility enforcer.  I removed this and it seems to have resolved the issue.
Here's a simpler repro:
https://plnkr.co/edit/ULEygEDsLiVP7qCZIIp7
Try switching out ```cola.js``` for ```cola1.js``` (with my fix) in ```index.html```

**Comment by doublemarked** [comment]
Hey @tgdwyer, nice to hear from you!

Sounds good, however I don't see `cola1.js` in the plnk.

**Comment by doublemarked** [comment]
Oops, I see you have also pushed a commit - I'll test w/ your latest and update in a bit.

**Comment by doublemarked** [comment]
Yes, tested and things do seem better! TYVM!
